version: '3.9'
services:
  server:
    container_name: server
    image: dp
    ports:
      - 3000:3000
      - 8000:8000
      - 8080:8080
    environment:
      REDIS_HOST: redis
      MYSQL_HOST: mysql
    depends_on:
      - redis
      - mysql
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
  mysql:
    image: mysql:latest
    secrets: 
      - my_secret2
    environment: 
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/my_secret2
      - MYSQL_DATABASE=nclouds
    ports:
      - 3306:3306
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
secrets:
  my_secret2: 
    file: ./my_secret.txt