version: '3'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    image: dp
    ports:
      - 3000:3000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 8000
      BIND: 0.0.0.0

