version: '3'
services:
  server:
    container_name: server
    image: dp
    ports:
      - 3000:3000
      - 8080:8080
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 8000
      BIND: 0.0.0.0
      MYSQL_HOST: mysql
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:latest
    restart: always
  mysql:
    image: mysql:latest
    environment: 
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE= nclouds
